# Generated by Django 4.1.7 on 2023-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableAclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNo', models.IntegerField()),
                ('Ename', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
